image: docker:stable

services:
- docker:dind

stages:
- build
- release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: registry.gitlab.com/nthienan/db-backup:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/nthienan/db-backup:latest

before_script:
  - docker login registry.gitlab.com -u gitlab-ci-token -p $CI_JOB_TOKEN

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
