sudo: required
language: python
services:
  - docker
env:
  global:
    - IMAGE_NAME=nthienan/db-backup

before_script:
  - docker pull $IMAGE_NAME || true
script:
  - docker build --pull --cache-from $IMAGE_NAME --tag $IMAGE_NAME .
after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
deploy:
  provider: script
  script: dcd --tag $(git rev-parse --short HEAD) --tag latest $IMAGE_NAME
