backup:
- db: MariaDB
  host: db
  port: 3306
  user: root
  password: mysql
  # name of databases to be backup
  databases:
  - test
  storages:
  - provider: Git
    # URL of git repository including access token in URL e.g. https://oauth2:<access_token>@gitlab.com/username/private-project
    url: https://oauth2:<access_token>@github.com/user/db-sync.git
    # whether storage provider supports versioning or not. If versioning is support then backup result will overwrite the previous one
    versioning: true
    # L20180812104500_UTC_monitoring.sqlocation where repo should be cloned into
    dir: /var/db-backup/data/git
  - provider: Local
    # Location where backup results should be stored
    dir: /var/db-backup/data/local
    # Number of backup file of a database will be kept. Older backup will be removed
    numberToKeep: 5
  trigger:
    # at 00:01 daily
    cron: 1 0 * * *
#    once: 2018-08-06 17:05:27
logging:
  level: INFO
